#!/bin/sh
#### PBS preamble

#PBS -N Halo_Only_Scan

#PBS -M fosterjw@umich.edu
#PBS -m abe

# Change the number of cores (ppn = 1), amount of memory, and walltime:

#PBS -l nodes=1:ppn=12,mem=16gb,walltime=48:00:00
#PBS -j oe
#PBS -V

#PBS -A bsafdi_flux
#PBS -q flux
#PBS -l qos=flux

#### End PBS preamble

# Put your job commands here:

echo "Starting job ...."
mpiexec -n 12 python /nfs/turbo/bsafdi/fosterjw/github/ABRA-DATA/MultiNestScan/Halo_Scan.py
